using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using QuoteSnap.Domain.Entities;

namespace QuoteSnap.Infrastructure.Pdf;

public class InvoicePdfDocument : IDocument
{
    private readonly Invoice _invoice;
    private readonly Business _business;

    public InvoicePdfDocument(
        Invoice invoice,
        Business business)
    {
        _invoice = invoice;
        _business = business;
    }

    public DocumentMetadata GetMetadata()
    {
        return DocumentMetadata.Default;
    }

    public void Compose(IDocumentContainer container)
    {
        container.Page(page =>
        {
            page.Size(PageSizes.A4);

            page.Margin(40);

            page.DefaultTextStyle(x =>
                x.FontSize(10));

            page.Header()
                .Element(ComposeHeader);

            page.Content()
                .PaddingVertical(20)
                .Element(ComposeContent);

            page.Footer()
                .AlignCenter()
                .Text(text =>
                {
                    text.Span("Generated by QuoteSnap • ");

                    text.CurrentPageNumber();

                    text.Span(" / ");

                    text.TotalPages();
                });
        });
    }

    private void ComposeHeader(IContainer container)
    {
        container.Row(row =>
        {
            row.RelativeItem()
                .Column(column =>
                {
                    column.Item()
                        .Text(_business.Name)
                        .FontSize(20)
                        .SemiBold();

                    if (!string.IsNullOrWhiteSpace(_business.Address))
                    {
                        column.Item()
                            .Text(_business.Address);
                    }

                    if (!string.IsNullOrWhiteSpace(_business.Email))
                    {
                        column.Item()
                            .Text(_business.Email);
                    }

                    if (!string.IsNullOrWhiteSpace(_business.Phone))
                    {
                        column.Item()
                            .Text(_business.Phone);
                    }
                });

            row.ConstantItem(180)
                .AlignRight()
                .Column(column =>
                {
                    column.Item()
                        .AlignRight()
                        .Text("INVOICE")
                        .FontSize(24)
                        .Bold();

                    column.Item()
                        .AlignRight()
                        .Text(_invoice.InvoiceNumber)
                        .FontSize(12)
                        .SemiBold();

                    column.Item()
                        .AlignRight()
                        .Text(
                            $"Issued: {_invoice.IssueDate:dd MMM yyyy}");

                    column.Item()
                        .AlignRight()
                        .Text(
                            $"Due: {_invoice.DueDate:dd MMM yyyy}");
                });
        });
    }

    private void ComposeContent(IContainer container)
    {
        container.Column(column =>
        {
            column.Spacing(20);

            column.Item()
                .Element(ComposeCustomer);

            column.Item()
                .Element(ComposeItems);

            column.Item()
                .AlignRight()
                .Width(250)
                .Element(ComposeTotals);

            if (!string.IsNullOrWhiteSpace(_invoice.Notes))
            {
                column.Item()
                    .Element(x =>
                        ComposeTextSection(
                            x,
                            "Notes",
                            _invoice.Notes));
            }

            if (!string.IsNullOrWhiteSpace(_invoice.Terms))
            {
                column.Item()
                    .Element(x =>
                        ComposeTextSection(
                            x,
                            "Terms",
                            _invoice.Terms));
            }

            column.Item()
                .Element(ComposePaymentDetails);
        });
    }

    private void ComposeCustomer(IContainer container)
    {
        container.Column(column =>
        {
            column.Item()
                .Text("BILL TO")
                .Bold();

            column.Item()
                .Text(_invoice.Customer.Name);

            if (!string.IsNullOrWhiteSpace(
                    _invoice.Customer.CompanyName))
            {
                column.Item()
                    .Text(_invoice.Customer.CompanyName);
            }

            if (!string.IsNullOrWhiteSpace(
                    _invoice.Customer.Email))
            {
                column.Item()
                    .Text(_invoice.Customer.Email);
            }

            if (!string.IsNullOrWhiteSpace(
                    _invoice.Customer.Phone))
            {
                column.Item()
                    .Text(_invoice.Customer.Phone);
            }

            if (!string.IsNullOrWhiteSpace(
                    _invoice.Customer.Address))
            {
                column.Item()
                    .Text(_invoice.Customer.Address);
            }
        });
    }

    private void ComposeItems(IContainer container)
    {
        container.Table(table =>
        {
            table.ColumnsDefinition(columns =>
            {
                columns.RelativeColumn(4);
                columns.RelativeColumn(1);
                columns.RelativeColumn(2);
                columns.RelativeColumn(2);
            });

            table.Header(header =>
            {
                header.Cell()
                    .Element(HeaderCell)
                    .Text("Description");

                header.Cell()
                    .Element(HeaderCell)
                    .AlignRight()
                    .Text("Qty");

                header.Cell()
                    .Element(HeaderCell)
                    .AlignRight()
                    .Text("Unit Price");

                header.Cell()
                    .Element(HeaderCell)
                    .AlignRight()
                    .Text("Total");
            });

            foreach (var item in _invoice.Items)
            {
                table.Cell()
                    .Element(BodyCell)
                    .Text(item.Description);

                table.Cell()
                    .Element(BodyCell)
                    .AlignRight()
                    .Text($"{item.Quantity:0.##}");

                table.Cell()
                    .Element(BodyCell)
                    .AlignRight()
                    .Text(Money(item.UnitPrice));

                table.Cell()
                    .Element(BodyCell)
                    .AlignRight()
                    .Text(Money(item.LineTotal));
            }
        });
    }

    private void ComposeTotals(IContainer container)
    {
        container.Column(column =>
        {
            TotalsRow(
                column,
                "Subtotal",
                _invoice.Subtotal);

            if (_invoice.DiscountAmount > 0)
            {
                TotalsRow(
                    column,
                    "Discount",
                    -_invoice.DiscountAmount);
            }

            if (_invoice.TaxAmount > 0)
            {
                var taxLabel =
                    string.IsNullOrWhiteSpace(_invoice.TaxName)
                        ? $"Tax ({_invoice.TaxRate:0.##}%)"
                        : $"{_invoice.TaxName} ({_invoice.TaxRate:0.##}%)";

                TotalsRow(
                    column,
                    taxLabel,
                    _invoice.TaxAmount);
            }

            column.Item()
                .PaddingTop(5)
                .BorderTop(1)
                .PaddingTop(5)
                .Row(row =>
                {
                    row.RelativeItem()
                        .Text("TOTAL")
                        .Bold();

                    row.RelativeItem()
                        .AlignRight()
                        .Text(Money(_invoice.Total))
                        .Bold();
                });

            TotalsRow(
                column,
                "Amount Paid",
                _invoice.AmountPaid);

            column.Item()
                .PaddingTop(5)
                .Row(row =>
                {
                    row.RelativeItem()
                        .Text("BALANCE DUE")
                        .Bold();

                    row.RelativeItem()
                        .AlignRight()
                        .Text(Money(_invoice.BalanceDue))
                        .Bold();
                });
        });
    }

    private void ComposePaymentDetails(
        IContainer container)
    {
        if (string.IsNullOrWhiteSpace(_business.BankName) &&
            string.IsNullOrWhiteSpace(_business.AccountNumber))
        {
            return;
        }

        container.Column(column =>
        {
            column.Item()
                .Text("PAYMENT DETAILS")
                .Bold();

            if (!string.IsNullOrWhiteSpace(_business.BankName))
            {
                column.Item()
                    .Text($"Bank: {_business.BankName}");
            }

            if (!string.IsNullOrWhiteSpace(
                    _business.AccountHolder))
            {
                column.Item()
                    .Text(
                        $"Account Holder: {_business.AccountHolder}");
            }

            if (!string.IsNullOrWhiteSpace(
                    _business.AccountNumber))
            {
                column.Item()
                    .Text(
                        $"Account Number: {_business.AccountNumber}");
            }

            if (!string.IsNullOrWhiteSpace(
                    _business.BranchCode))
            {
                column.Item()
                    .Text(
                        $"Branch Code: {_business.BranchCode}");
            }
        });
    }

    private static void ComposeTextSection(
        IContainer container,
        string title,
        string value)
    {
        container.Column(column =>
        {
            column.Item()
                .Text(title.ToUpperInvariant())
                .Bold();

            column.Item()
                .Text(value);
        });
    }

    private void TotalsRow(
        ColumnDescriptor column,
        string label,
        decimal value)
    {
        column.Item()
            .Row(row =>
            {
                row.RelativeItem()
                    .Text(label);

                row.RelativeItem()
                    .AlignRight()
                    .Text(Money(value));
            });
    }

    private string Money(decimal amount)
    {
        return $"{_invoice.CurrencyCode} {amount:N2}";
    }

    private static IContainer HeaderCell(
        IContainer container)
    {
        return container
            .BorderBottom(1)
            .PaddingVertical(5)
            .DefaultTextStyle(x => x.SemiBold());
    }

    private static IContainer BodyCell(
        IContainer container)
    {
        return container
            .BorderBottom(0.5f)
            .PaddingVertical(7);
    }
}