using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using QuoteSnap.Domain.Entities;

namespace QuoteSnap.Infrastructure.Pdf;

public class QuotePdfDocument : IDocument
{
    private readonly Quote _quote;
    private readonly Business _business;

    public QuotePdfDocument(
        Quote quote,
        Business business)
    {
        _quote = quote;
        _business = business;
    }

    public DocumentMetadata GetMetadata()
        => DocumentMetadata.Default;

    public void Compose(IDocumentContainer container)
    {
        container.Page(page =>
        {
            page.Size(PageSizes.A4);
            page.Margin(40);

            page.DefaultTextStyle(x =>
                x.FontSize(10));

            page.Header()
                .Element(ComposeHeader);

            page.Content()
                .PaddingVertical(20)
                .Element(ComposeContent);

            page.Footer()
                .AlignCenter()
                .Text(text =>
                {
                    text.Span("Generated by QuoteSnap • ");
                    text.CurrentPageNumber();
                    text.Span(" / ");
                    text.TotalPages();
                });
        });
    }

    private void ComposeHeader(IContainer container)
    {
        container.Row(row =>
        {
            row.RelativeItem()
                .Column(column =>
                {
                    column.Item()
                        .Text(_business.Name)
                        .FontSize(20)
                        .SemiBold();

                    if (!string.IsNullOrWhiteSpace(_business.Address))
                        column.Item().Text(_business.Address);

                    if (!string.IsNullOrWhiteSpace(_business.Email))
                        column.Item().Text(_business.Email);

                    if (!string.IsNullOrWhiteSpace(_business.Phone))
                        column.Item().Text(_business.Phone);
                });

            row.ConstantItem(180)
                .AlignRight()
                .Column(column =>
                {
                    column.Item()
                        .AlignRight()
                        .Text("QUOTE")
                        .FontSize(24)
                        .Bold();

                    column.Item()
                        .AlignRight()
                        .Text(_quote.QuoteNumber)
                        .SemiBold();

                    column.Item()
                        .AlignRight()
                        .Text(
                            $"Issued: {_quote.IssueDate:dd MMM yyyy}");

                    column.Item()
                        .AlignRight()
                        .Text(
                            $"Valid until: {_quote.ValidUntil:dd MMM yyyy}");
                });
        });
    }

    private void ComposeContent(IContainer container)
    {
        container.Column(column =>
        {
            column.Spacing(20);

            column.Item()
                .Element(ComposeCustomer);

            column.Item()
                .Element(ComposeItems);

            column.Item()
                .AlignRight()
                .Width(250)
                .Element(ComposeTotals);

            if (!string.IsNullOrWhiteSpace(_quote.Notes))
            {
                column.Item()
                    .Element(x =>
                        ComposeSection(
                            x,
                            "Notes",
                            _quote.Notes));
            }

            if (!string.IsNullOrWhiteSpace(_quote.Terms))
            {
                column.Item()
                    .Element(x =>
                        ComposeSection(
                            x,
                            "Terms",
                            _quote.Terms));
            }
        });
    }

    private void ComposeCustomer(IContainer container)
    {
        container.Column(column =>
        {
            column.Item()
                .Text("QUOTE FOR")
                .Bold();

            column.Item()
                .Text(_quote.Customer.Name);

            if (!string.IsNullOrWhiteSpace(
                    _quote.Customer.CompanyName))
            {
                column.Item()
                    .Text(_quote.Customer.CompanyName);
            }

            if (!string.IsNullOrWhiteSpace(
                    _quote.Customer.Email))
            {
                column.Item()
                    .Text(_quote.Customer.Email);
            }

            if (!string.IsNullOrWhiteSpace(
                    _quote.Customer.Phone))
            {
                column.Item()
                    .Text(_quote.Customer.Phone);
            }

            if (!string.IsNullOrWhiteSpace(
                    _quote.Customer.Address))
            {
                column.Item()
                    .Text(_quote.Customer.Address);
            }
        });
    }

    private void ComposeItems(IContainer container)
    {
        container.Table(table =>
        {
            table.ColumnsDefinition(columns =>
            {
                columns.RelativeColumn(4);
                columns.RelativeColumn(1);
                columns.RelativeColumn(2);
                columns.RelativeColumn(2);
            });

            table.Header(header =>
            {
                header.Cell()
                    .Element(HeaderCell)
                    .Text("Description");

                header.Cell()
                    .Element(HeaderCell)
                    .AlignRight()
                    .Text("Qty");

                header.Cell()
                    .Element(HeaderCell)
                    .AlignRight()
                    .Text("Unit Price");

                header.Cell()
                    .Element(HeaderCell)
                    .AlignRight()
                    .Text("Total");
            });

            foreach (var item in _quote.Items)
            {
                table.Cell()
                    .Element(BodyCell)
                    .Text(item.Description);

                table.Cell()
                    .Element(BodyCell)
                    .AlignRight()
                    .Text($"{item.Quantity:0.##}");

                table.Cell()
                    .Element(BodyCell)
                    .AlignRight()
                    .Text(Money(item.UnitPrice));

                table.Cell()
                    .Element(BodyCell)
                    .AlignRight()
                    .Text(Money(item.LineTotal));
            }
        });
    }

    private void ComposeTotals(IContainer container)
    {
        container.Column(column =>
        {
            TotalsRow(
                column,
                "Subtotal",
                _quote.Subtotal);

            if (_quote.DiscountAmount > 0)
            {
                TotalsRow(
                    column,
                    "Discount",
                    -_quote.DiscountAmount);
            }

            if (_quote.TaxAmount > 0)
            {
                var label =
                    string.IsNullOrWhiteSpace(_quote.TaxName)
                        ? $"Tax ({_quote.TaxRate:0.##}%)"
                        : $"{_quote.TaxName} ({_quote.TaxRate:0.##}%)";

                TotalsRow(
                    column,
                    label,
                    _quote.TaxAmount);
            }

            column.Item()
                .PaddingTop(5)
                .BorderTop(1)
                .PaddingTop(5)
                .Row(row =>
                {
                    row.RelativeItem()
                        .Text("TOTAL")
                        .Bold();

                    row.RelativeItem()
                        .AlignRight()
                        .Text(Money(_quote.Total))
                        .Bold();
                });
        });
    }

    private static void ComposeSection(
        IContainer container,
        string title,
        string value)
    {
        container.Column(column =>
        {
            column.Item()
                .Text(title.ToUpperInvariant())
                .Bold();

            column.Item()
                .Text(value);
        });
    }

    private void TotalsRow(
        ColumnDescriptor column,
        string label,
        decimal amount)
    {
        column.Item()
            .Row(row =>
            {
                row.RelativeItem().Text(label);

                row.RelativeItem()
                    .AlignRight()
                    .Text(Money(amount));
            });
    }

    private string Money(decimal amount)
        => $"{_quote.CurrencyCode} {amount:N2}";

    private static IContainer HeaderCell(
        IContainer container)
    {
        return container
            .BorderBottom(1)
            .PaddingVertical(5)
            .DefaultTextStyle(x => x.SemiBold());
    }

    private static IContainer BodyCell(
        IContainer container)
    {
        return container
            .BorderBottom(0.5f)
            .PaddingVertical(7);
    }
}