using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using QuoteSnap.Domain.Entities;

namespace QuoteSnap.Infrastructure.Pdf;

public class ReceiptPdfDocument : IDocument
{
    private readonly Receipt _receipt;
    private readonly Business _business;

    public ReceiptPdfDocument(
        Receipt receipt,
        Business business)
    {
        _receipt = receipt;
        _business = business;
    }

    public DocumentMetadata GetMetadata()
        => DocumentMetadata.Default;

    public void Compose(IDocumentContainer container)
    {
        container.Page(page =>
        {
            page.Size(PageSizes.A4);
            page.Margin(40);

            page.DefaultTextStyle(x =>
                x.FontSize(10));

            page.Header()
                .Element(ComposeHeader);

            page.Content()
                .PaddingVertical(25)
                .Element(ComposeContent);

            page.Footer()
                .AlignCenter()
                .Text(text =>
                {
                    text.Span("Generated by QuoteSnap • ");
                    text.CurrentPageNumber();
                    text.Span(" / ");
                    text.TotalPages();
                });
        });
    }

    private void ComposeHeader(IContainer container)
    {
        container.Row(row =>
        {
            row.RelativeItem()
                .Column(column =>
                {
                    column.Item()
                        .Text(_business.Name)
                        .FontSize(20)
                        .SemiBold();

                    if (!string.IsNullOrWhiteSpace(
                            _business.Address))
                    {
                        column.Item()
                            .Text(_business.Address);
                    }

                    if (!string.IsNullOrWhiteSpace(
                            _business.Email))
                    {
                        column.Item()
                            .Text(_business.Email);
                    }

                    if (!string.IsNullOrWhiteSpace(
                            _business.Phone))
                    {
                        column.Item()
                            .Text(_business.Phone);
                    }
                });

            row.ConstantItem(180)
                .AlignRight()
                .Column(column =>
                {
                    column.Item()
                        .AlignRight()
                        .Text("RECEIPT")
                        .FontSize(24)
                        .Bold();

                    column.Item()
                        .AlignRight()
                        .Text(_receipt.ReceiptNumber)
                        .SemiBold();

                    column.Item()
                        .AlignRight()
                        .Text(
                            $"{_receipt.ReceiptDate:dd MMM yyyy}");
                });
        });
    }

    private void ComposeContent(IContainer container)
    {
        container.Column(column =>
        {
            column.Spacing(20);

            column.Item()
                .Element(ComposeCustomer);

            column.Item()
                .Element(ComposePayment);

            column.Item()
                .PaddingTop(10)
                .BorderTop(1)
                .PaddingTop(15)
                .Row(row =>
                {
                    row.RelativeItem()
                        .Text("AMOUNT RECEIVED")
                        .FontSize(14)
                        .Bold();

                    row.RelativeItem()
                        .AlignRight()
                        .Text(Money(_receipt.Amount))
                        .FontSize(16)
                        .Bold();
                });

            column.Item()
                .PaddingTop(20)
                .Text(
                    "Thank you. This receipt confirms that payment has been received.")
                .Italic();
        });
    }

    private void ComposeCustomer(IContainer container)
    {
        container.Column(column =>
        {
            column.Item()
                .Text("RECEIVED FROM")
                .Bold();

            column.Item()
                .Text(
                    _receipt.Invoice.Customer.Name);

            if (!string.IsNullOrWhiteSpace(
                    _receipt.Invoice.Customer.CompanyName))
            {
                column.Item()
                    .Text(
                        _receipt.Invoice.Customer.CompanyName);
            }

            if (!string.IsNullOrWhiteSpace(
                    _receipt.Invoice.Customer.Email))
            {
                column.Item()
                    .Text(
                        _receipt.Invoice.Customer.Email);
            }

            if (!string.IsNullOrWhiteSpace(
                    _receipt.Invoice.Customer.Phone))
            {
                column.Item()
                    .Text(
                        _receipt.Invoice.Customer.Phone);
            }
        });
    }

    private void ComposePayment(IContainer container)
    {
        container.Column(column =>
        {
            column.Item()
                .Text("PAYMENT DETAILS")
                .Bold();

            DetailRow(
                column,
                "Invoice",
                _receipt.Invoice.InvoiceNumber);

            DetailRow(
                column,
                "Payment Date",
                _receipt.Payment.PaymentDate
                    .ToString("dd MMM yyyy"));

            DetailRow(
                column,
                "Payment Method",
                _receipt.Payment.Method.ToString());

            if (!string.IsNullOrWhiteSpace(
                    _receipt.Payment.Reference))
            {
                DetailRow(
                    column,
                    "Reference",
                    _receipt.Payment.Reference);
            }

            if (!string.IsNullOrWhiteSpace(
                    _receipt.Payment.Notes))
            {
                DetailRow(
                    column,
                    "Notes",
                    _receipt.Payment.Notes);
            }
        });
    }

    private static void DetailRow(
        ColumnDescriptor column,
        string label,
        string value)
    {
        column.Item()
            .PaddingVertical(3)
            .Row(row =>
            {
                row.ConstantItem(130)
                    .Text(label)
                    .SemiBold();

                row.RelativeItem()
                    .Text(value);
            });
    }

    private string Money(decimal amount)
    {
        return $"{_receipt.CurrencyCode} {amount:N2}";
    }
}